name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build sonar-sweep
      run: cargo build --verbose
      working-directory: sonar-sweep
    - name: Run tests sonar-sweep
      run: cargo test --verbose
      working-directory: sonar-sweep
    - name: Build dive
      run: cargo build --verbose
      working-directory: dive
    - name: Run tests dive
      run: cargo test --verbose
      working-directory: dive
    - name: Build binary-diagnostic
      run: cargo build --verbose
      working-directory: binary-diagnostic
    - name: Run tests binary-diagnostic
      run: cargo test --verbose
      working-directory: binary-diagnostic
