name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build sonar-sweep
      run: cargo build --verbose
      working-directory: sonar-sweep
    - name: Run tests sonar-sweep
      run: cargo test --verbose
      working-directory: sonar-sweep
    - name: Build dive
      run: cargo build --verbose
      working-directory: dive
    - name: Run tests dive
      run: cargo test --verbose
      working-directory: dive
    - name: Build binary-diagnostic
      run: cargo build --verbose
      working-directory: binary-diagnostic
    - name: Run tests binary-diagnostic
      run: cargo test --verbose
      working-directory: binary-diagnostic
    - name: Build bingo
      run: cargo build --verbose
      working-directory: bingo
    - name: Run tests bingo
      run: cargo test --verbose
      working-directory: bingo
    - name: Build hydrovent
      run: cargo build --verbose
      working-directory: hydrovent
    - name: Run tests hydrovent
      run: cargo test --verbose
      working-directory: hydrovent
    - name: Build lanternfish
      run: cargo build --verbose
      working-directory: lanternfish
    - name: Run tests lanternfish
      run: cargo test --verbose
      working-directory: lanternfish
    - name: Build whales
      run: cargo build --verbose
      working-directory: whales
    - name: Run tests whales
      run: cargo test --verbose
      working-directory: whales
    - name: Build seven-segment
      run: cargo build --verbose
      working-directory: seven-segment
    - name: Run tests seven-segment
      run: cargo test --verbose
      working-directory: seven-segment
    - name: Build smokebasin
      run: cargo build --verbose
      working-directory: smokebasin
    - name: Run tests smokebasin
      run: cargo test --verbose
      working-directory: smokebasin
    - name: Build syntax-scoring
      run: cargo build --verbose
      working-directory: syntax-scoring
    - name: Run tests syntax-scoring
      run: cargo test --verbose
      working-directory: syntax-scoring
    - name: Build octopus
      run: cargo build --verbose
      working-directory: octopus
    - name: Run tests octopus
      run: cargo test --verbose
      working-directory: octopus
    - name: Build passage
      run: cargo build --verbose
      working-directory: passage
    - name: Run tests passage
      run: cargo test --verbose
      working-directory: passage
    - name: Build origami
      run: cargo build --verbose
      working-directory: origami
    - name: Run tests origami
      run: cargo test --verbose
      working-directory: origami
    - name: Build polymerization
      run: cargo build --verbose
      working-directory: polymerization
    - name: Run tests polymerization
      run: cargo test --verbose
      working-directory: polymerization
    - name: Build chiton
      run: cargo build --verbose
      working-directory: chiton
    - name: Run tests chiton
      run: cargo test --verbose
      working-directory: chiton
